name: FirstWorkflow
on:  push

jobs:
  task1: 
    runs-on: ubuntu-latest

    steps:
    - name: Clone repo
      uses: actions/checkout@v3

    - name: setup pyhton
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    - name: Run a py script
      run: python functionExamples/basicFunctions.py
      
    - name: Run a second script  
      run: python functionExamples/stringFuntions.py
      
      
    
